### ISSUE TITLE
For environment

### ISSUE THREAD

**Issue by xb-li** [xxlya/BrainGNN_Pytorch#13]
Hello，I encountered some issues while running file 03-main.py, as shown below:
Traceback (most recent call last):
  File "03-main.py", line 203, in <module>
    tr_loss, s1_arr, s2_arr, w1, w2 = train(epoch)
  File "03-main.py", line 130, in train
    output, w1, w2, s1, s2 = model(data.x, data.edge_index, data.batch, data.edge_attr, data.pos)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/BrainGNN/net/braingnn.py", line 63, in forward
    x = self.conv2(x, edge_index, edge_attr, pos)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/BrainGNN/net/braingraphconv.py", line 55, in forward
    return self.propagate(edge_index, size=size, x=x,
  File "/root/autodl-tmp/BrainGNN/net/brainmsgpassing.py", line 126, in propagate
    out = self.message(*message_args)
  File "/root/autodl-tmp/BrainGNN/net/braingraphconv.py", line 59, in message
    edge_weight = softmax(edge_weight, edge_index_i, ptr, size_i)
RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)

nvrtc compilation failed: 

I hope to receive some help.

**Comment by cibimo** [comment]
```
conda install cudatoolkit=11.8
pip install torch==1.7.1+cu110 --index-url https://download.pytorch.org/whl
```
